name: 'Draft'
description: 'No description.'
inputs:
  token:
    description: 'GitHub token used by action.'
    default: ${{ github.token }}
    required: true
  repository:
    description: 'Owner and repository name. For example, "Codertocat/Hello-World".'
    default: ${{ github.repository }}
    required: true
  unreleased:
    description: 'Title of the unreleased milestone.'
    default: Unreleased
    required: true
  release:
    description: 'Title of the new released milestone.'
    required: true
outputs:
  result:
    description: 'Action result.'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'box'  
  color: 'gray-dark'
